[package]
name = "load_secrets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.55.0"
aws-sdk-secretsmanager = "0.25.1"
tokio = { version = "1.27.0", features = ["full"] }
